In [4]:
import numpy as np    #importing numpy library

def ATH(lst,N):           #vandermonde matrix calculation function
    x=np.array(lst)
    output_matrix=np.vander(x,N)
    print(output_matrix)
    
input_lst=[1,2,4,5]      #input list

N=int(input("Enter number of columns in matrix"))     #getting number of columns from user

ATH(input_lst,N)     #calling functions

Enter number of columns in matrix3
[[ 1  1  1]
 [ 4  2  1]
 [16  4  1]
 [25  5  1]]
